name: CI

on:
  push:
    branches: [ master, development ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/compile.yml'

  pull_request:
    branches: [ master, development ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/compile.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Nuget
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      working-directory: src
      run: |
        dotnet restore --disable-parallel --locked-mode
        dotnet build --disable-parallel --configuration Release
