name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3
      with:
         versionSpec: '5.3.x'

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      working-directory: src
      run: |
        dotnet restore --disable-parallel --locked-mode
        dotnet build --disable-parallel --configuration Release

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3

    - name: Publish Nuget
      run: |
        dotnet nuget push ./src/bin/Release/qlik-sseapi.${{ steps.gitversion.outputs.semVer }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: '${{ github.event.release.upload_url }}' 
        asset_path: ./src/bin/Release/qlik-sseapi.${{ steps.gitversion.outputs.semVer }}.nupkg
        asset_name: qlik-connectapi.${{ steps.gitversion.outputs.semVer }}.nupkg
        asset_content_type: application/zip
